My first Microverse Capstone project
glorymugizi/uganda_smart_digital_id_conference pull request #1
Opened 2023-01-05 12:22 UTC by glorymugizi

Hello, using a design by Shin Cindy (`https://www.behance.net/gallery/29845175/CC-Global-Summit-2015`). I created a website that is fully responsive on both mobile and desktop. The project is similar to a real-world project and the design was followed as though it was the client's requirement. The aim of the project was to test what is covered in module one of the Microverse syllabus.

Thank you for reviewing my PR.

2023-01-05 14:36 UTC, christianbiring1 requested changes
Hi @glorymugizi , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![163947610-e4d849d5-e69c-49b9-90bd-a4191f4e2856](https://user-images.githubusercontent.com/97100091/210803745-fedafcc2-c0bb-4de1-a6fe-e271b29a6016.gif)

## Suggested changes
- [ ] Kindly make sure you stick to the design, the spacing(margin, padding), and font(weight, size, and family) need to be similar to the design.
`FONT-FAMILLY`
![image](https://user-images.githubusercontent.com/97100091/210804278-8e990f80-4377-467d-8bf5-444d9ef1602c.png)
`COLOR SWATCH`
![image](https://user-images.githubusercontent.com/97100091/210804339-51f429f2-4e32-47a0-89af-fcaf4ec25a8d.png)

_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] `Reducing the size of your images since they are weight and may cause bad user experience to the user using slow network connexion`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-01-05 14:36 UTC, christianbiring1 commented on styles.css
> +  }
- [ ] Kindly make sure you stick to the design as much as possible. the spacing (margin, padding) is supposed to be almost similar to the original design. as you may notice how your text is not centered and the font-weight is quite different from the original template. please fix that. 
- [ ] It would be nicer to simplify the background property in one short syntax.
`hint: background: [color] [image] [repeat] [position] [attachment];`

Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210787152-816666a1-629f-4f18-9b6b-044f1b4c7e1e.png)

Original design :point_down: 
![Screenshot from 2023-01-05 14-54-08](https://user-images.githubusercontent.com/97100091/210787091-3662e72b-84f7-41ea-9b86-2e026c23bfa5.png)

2023-01-05 14:36 UTC, christianbiring1 commented on styles.css
> +    width: 5rem;
- [ ] You may consider adding the underline under the `program title` as it is in the template and also make sure the `font(size and weight and family)` used on the page is similar to the one used in the design 
Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210788556-5be1a153-fc9e-40b9-a365-cf137008ee84.png)
![image](https://user-images.githubusercontent.com/97100091/210788835-0d96839e-9a24-46b8-9376-f6e65cb8bd75.png)

Original design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210788382-61fef32e-28c9-42e3-a567-e376f47fd015.png)
![image](https://user-images.githubusercontent.com/97100091/210788903-69ac1625-2c23-458f-9638-a93d80abf360.png)

2023-01-05 14:36 UTC, christianbiring1 commented on styles.css
> +    height: 2.5rem;
- [ ] Kindly make sure you place the chasse image behind the partners as it is on the design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210790132-d929d956-6d59-45dc-9717-99bbd1024c32.png)

[OPTIONAL]
- [ ] To make your images responsible you may consider using a `height:auto` so that they may be clear for a better user experience or you may consider adding the `object property set to fit`
Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210789778-3f397c48-3e6b-4110-9d9c-4e461d694f22.png)

2023-01-05 14:36 UTC, christianbiring1 commented on styles.css
> +  .partners {
- [ ] Kindly make sure your partner's section has enough `margin`(`top, left, right, bottom,)` and it's well centered as is the case in the original design 

Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210790878-583ca355-152b-4316-8f82-e716acc33198.png)

Original design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210790985-e7791b33-ae73-4562-9750-596f708aaf64.png)

2023-01-05 14:36 UTC, christianbiring1 commented on styles.css
> +    font-weight: bolder;
- [ ] Kindly consider using the same font, color and the red underline on your section's titles
- [ ] also make sure you have some text on the right of the footer section as it is in the original design. and why not add some more partner to make your design looks great :smile: 

Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210791772-24c4f797-170b-47ec-b7f6-48765d1f8e31.png)

original design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210791672-4ac420e1-14f2-4a03-b94b-f1e0dcf8c6fe.png)

2023-01-05 14:36 UTC, christianbiring1 commented on about.css
> +  }
- [ ] Kindy make sure you stick to the template as much as possible. you may consider increasing the weight of your font and also make sure the pages both looks kind of similar.
- [ ] You also consider using a font size a little bit similar to the original design 

Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210793571-05b0860c-95da-4d1b-8370-9faeef8b48b0.png)

Original design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210793688-c9c729e6-1f0e-46d4-93dc-459132865855.png)

2023-01-05 14:36 UTC, christianbiring1 commented on about.css
> +    color: white;
- [ ] Kindly consider reducing the width of your images and adding some margin around that section to make them look similar to the design.

Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210794877-f4f3d5d0-78e6-49ba-af76-c61ddf19f489.png)

Original design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210795167-96152b2f-09a6-4f27-b069-750161df0f3e.png)

2023-01-05 14:36 UTC, christianbiring1 commented on about.css
> +  }
- [ ] You may also consider adding some dummy text on your footer and positioning the elements as they are in the original template.

Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210795648-073cb52f-3380-4714-b54e-4a2424a7af15.png)

Original design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210795758-daf23823-c0d1-4c42-b5d4-e4fb4200c6fa.png)

2023-01-05 14:36 UTC, christianbiring1 commented on styles.css
> +  width: 100%;
[OPTIONAL]
- [ ] For a better user experience you may consider making the navigation bar fixed on the page so that the user may jump from one section to another easily no matter the scroll position they have reached instead of scrolling all the way to the top of the page to reach the `menu`

2023-01-05 14:36 UTC, christianbiring1 commented on about.css
> +
- [ ] Kindly make sure you stick to the design as much as possible. You may consider `aligning the text on the center` in your about detail and also make sure you always use a similar `font (size, weight, and family: cocogoose or Lato)`

Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210799728-8214606e-d1cc-407c-907a-8bfd9b01758f.png)

Original design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210799510-d3940551-c657-431f-96f0-cf8a892e4851.png)


`Hint: You will need to download the font-family: cocogoose`

2023-01-05 14:36 UTC, christianbiring1 commented on about.css
> +    text-align: center;
- [ ] Kindly make sure your text is centered as it is in the design.
`Hint: You may consider grabbing them inside a container and centering it` :smile: 

Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210800060-44607636-b6aa-4177-998f-16277273801e.png)

Original design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210800246-ac642b5b-1b74-4066-a66f-77d6add3fd11.png)

2023-01-05 14:36 UTC, christianbiring1 commented on scripts.js
> +`;
- [ ] As is the case in the original template, kindly make sure when the page loads the user can only see two speakers on the page. and the `SHOW MORE` button. once clicked they can be able to see the all speaker's lists.

Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210803349-56b06332-c973-43d8-8950-da8ab3f16983.png)


Original design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/210803256-a98293e0-f406-4b41-bb13-e5d7d5c22d2e.png)


`Hint: With your approach, you may consider splitting the speakers in two different arrays: the one to show the initial list and the other to show the remaining list once the button is clicked. You may consider putting the second render in a function which will be called once the button is cliked ` :smile:

2023-01-06 09:00 UTC, Olamarx requested changes
Hi @glorymugizi,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media3.giphy.com/media/hXz6GN0ZilLwhgLo49/giphy.gif"/>

 ## Highlights
- Linters passed ✔️ 
- Readme file ✔️ 
- GitHub flow ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 09:00 UTC, Olamarx commented on scripts.js
> +});
- [ ] As suggested by the previous reviewer, kindly make the partner's section has enough margin(top, left, right, bottom,) and it's well centered as is the case in the original design. Remember it has three rows and two column but I can see two rows and three columns in your work.

### Your work
![image](https://user-images.githubusercontent.com/86200356/210963417-62bc6694-f480-4578-89e5-1bbea291aaac.png)

### Original design
![image](https://user-images.githubusercontent.com/86200356/210963525-b0f0fe64-cc18-4ce3-8291-3ce4615e9839.png)

2023-01-06 09:00 UTC, Olamarx commented on index.html
> +      </div>
- [ ] Good one adding the text as observed by the previous reviewer, however, you forgot to style it as the original design is. The original design added a justify content property which is missing here and makes the content not organized. Kindly fix this up.
- [ ] This applies to the about footer too.

### Your design
![image](https://user-images.githubusercontent.com/86200356/210964623-41a1d5a0-c159-41c1-94d0-ab6118290f3c.png)


### Original Design
![image](https://user-images.githubusercontent.com/86200356/210964586-5fe956d3-f9f2-4f93-a006-0b3b03cc672a.png)

2023-01-06 10:37 UTC, Abenezer-Tilahun commented on scripts.js
> +});
Fixed.

2023-01-06 10:38 UTC, Abenezer-Tilahun commented on index.html
> +      </div>
Fixed.

2023-01-06 10:40 UTC, Abenezer-Tilahun approved these changes
Hi @glorymugizi 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Github-Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ Good job for Implemented Suggested changes . 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 10:43 UTC, merged